language: python

python:
  - "2.7"
  - "3.4"

sudo: false

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install numpy pytest
  - python setup.py install

script:
  - pwd
  - export PATH="$(pwd)/bin:$HOME/miniconda/bin:$PATH"
  # Download test Data
  - mkdir -p $HOME/data
  - pushd $HOME/data
  - wget http://mattmahoney.net/dc/text8.zip -O text8.zip
  - unzip text8.zip
  - head -c 1000000 text8 > text
  - popd
  # py.test
  - cd word2vec/tests
  - py.test  -s -vv
